### ISSUE TITLE
Not working with Lumen 5.4

### ISSUE THREAD

**Issue by BogdanHossu** [codedge/lumen-countries#2]
Trying to make it work with Lumen 5.4, first error was that share() is not define, which I have modified with singleton(). Than I get the error that optimize is not defined. Looks like the command php artisan optimize is called and Lumen does not have this command.

**Comment by codedge** [comment]
@BogdanHossu should be compatible now, tested with latest Lumen version 5.4.6

**Comment by BogdanHossu** [comment]
When following the installation step by step, I encounter this error 
`Class 'Codedge\Countries\CountriesServiceProvider' not found`

Do you think I am doing something wrong? The provider is registered into my bootstrap/app.php.

**Comment by codedge** [comment]
Hmm.. sounds strange. Please run `composer update` and `composer dump-autoload`. After that it should work.

**Comment by BogdanHossu** [comment]
Unfortunately I have tried this a lot of times but with no success.

**Comment by codedge** [comment]
I'll updated the package - there was sth. wrong with proper loading, as you mentioned. Please run `composer update` again and fetch the latest `1.6.1` version

**Comment by BogdanHossu** [comment]
Thank you @codedge, I can confirm that now it worked for me.
